# Generated by Django 5.1.4 on 2024-12-07 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimizationResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("demand", models.FloatField()),
                ("result", models.JSONField(blank=True, null=True)),
                ("total_cost", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyAsset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("max_capacity", models.FloatField()),
                ("cost_per_mwh", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
